CREATE DATABASE IF NOT EXISTS moah_core DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

USE moah_core;

CREATE TABLE IF NOT EXISTS user (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(128) UNIQUE,
    password VARCHAR(255),
    nickname VARCHAR(32) NULL DEFAULT NULL,
    username VARCHAR(32),
    avatar VARCHAR(10) NULL DEFAULT NULL,  -- TODO: foreign key from saved images
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    flags TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS session (
    refresh_token CHAR(64) UNIQUE,
    user INT UNSIGNED,
    device_identifier CHAR(64),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user) REFERENCES user(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS node (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    type TINYINT UNSIGNED,
    url VARCHAR(256) UNIQUE
);

CREATE TABLE IF NOT EXISTS media (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    type TINYINT UNSIGNED,
    author INT UNSIGNED,
    node_id INT,
    FOREIGN KEY (author) REFERENCES user(id) ON DELETE NO ACTION,
    FOREIGN KEY (node_id) REFERENCES node(id) ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS tag (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(32),
    flags TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS media_tag (
    media_id INT UNSIGNED,
    tag_id INT UNSIGNED,
    FOREIGN KEY (media_id) REFERENCES media(id) ON DELETE CASCADE,
    FOREIGN KEY (tag_id) REFERENCES tag(id) ON DELETE CASCADE
);
